create table if not exists job_descriptions (
    id bigint generated by default as identity primary key,
    title text not null,
    description text not null,
    required_skills jsonb default '[]'::jsonb,
    created_at timestamptz default now(),
    updated_at timestamptz default now()
);

create table if not exists candidate_evaluations (
    id bigint generated by default as identity primary key,
    candidate_id bigint not null references candidates(id) on delete cascade,
    job_description_id bigint not null references job_descriptions(id) on delete cascade,

    resume_match_score numeric default 0,
    project_relevance_score numeric default 0,
    research_relevance_score numeric default 0,
    cgpa_score numeric default 0,
    logical_aptitude_score numeric default 0,
    coding_test_score numeric default 0,
    overall_score numeric default 0,

    matched_skills jsonb default '[]'::jsonb,
    missing_skills jsonb default '[]'::jsonb,
    recommendation text,
    explanation text,

    created_at timestamptz default now(),
    updated_at timestamptz default now(),

    unique(candidate_id, job_description_id)
);


alter table candidates
add column if not exists resume_text text;

alter table candidates
add column if not exists extracted_skills jsonb default '[]'::jsonb;

alter table candidates
add column if not exists resume_file_path text;

alter table candidates
add column if not exists resume_processing_status text default 'pending';

alter table candidates
add column if not exists resume_processed_at timestamptz;


delete from candidates;

alter table candidates
drop constraint if exists candidates_email_key;

alter table candidates
add constraint candidates_s_no_key unique (s_no);

create table if not exists candidates (
    id bigint generated by default as identity primary key,
    s_no integer,
    name text not null,
    email text not null unique,
    college text,
    branch text,
    cgpa numeric,
    best_ai_project text,
    research_work text,
    github text,
    resume text,
    test_la numeric,
    test_code numeric,
    status text default 'uploaded',
    created_at timestamptz default now(),
    updated_at timestamptz default now()
);

create table if not exists github_analyses (
    id bigint generated by default as identity primary key,

    candidate_id bigint not null
        references candidates(id)
        on delete cascade,

    github_username text,
    profile_url text,

    public_repositories integer default 0,
    analyzed_repositories integer default 0,
    followers integer default 0,
    following integer default 0,

    total_stars integer default 0,
    total_forks integer default 0,
    recent_commits integer default 0,
    repositories_with_readme integer default 0,

    languages jsonb default '{}'::jsonb,
    top_repositories jsonb default '[]'::jsonb,

    repository_quality_score numeric default 0,
    documentation_score numeric default 0,
    activity_score numeric default 0,
    diversity_score numeric default 0,
    github_score numeric default 0,

    strengths jsonb default '[]'::jsonb,
    concerns jsonb default '[]'::jsonb,
    explanation text,

    status text default 'pending',
    analyzed_at timestamptz,

    created_at timestamptz default now(),
    updated_at timestamptz default now(),

    unique(candidate_id)
);

alter table candidate_evaluations
add column if not exists github_score numeric;

alter table candidate_evaluations
add column if not exists github_profile_available boolean default false;

alter table candidate_evaluations
alter column github_score drop not null;

alter table candidate_evaluations
alter column github_score drop default;
